// AUTO-GENERATED by: npm run init
// 'folder' is the exact Cloudinary folder — DO NOT edit it.
// 'title' and 'order' are safe to change.
// Add a Google Photos album link (photosAlbumUrl) and YouTube links (videos)
// wherever you have them, e.g.:
//   videos: [{ title: 'झंडारोहण', url: 'https://youtu.be/XXXXXXXXXXX' }],
// Then run: npm run seed

export default [
  { order: 1, title: "प्रातः कालीन प्रार्थना सत्र", folder: "प्रातः क़ालीन प्रार्थना सत्र", photosAlbumUrl: '', videos: [] },
  { order: 2, title: "सांयकालीन बाल सभा", folder: "संयकालीन बाल सभा", photosAlbumUrl: '', videos: [] },
  { order: 3, title: "प्रेरणादाई मध्यान भोजन सत्र", folder: "मध्यान भोजन सत्र", photosAlbumUrl: '', videos: [] },
  { order: 4, title: "स्वतंत्रता दिवस 2025", folder: "स्वतंत्रता दिवस 2025", photosAlbumUrl: '', videos: [] },
  { order: 5, title: "गणतंत्र दिवस समारोह 2026", folder: "गणतंत्र दिवस समारोह 2026", photosAlbumUrl: '', videos: [] },
  { order: 6, title: "विद्यालय वार्षिकोत्सव 2026", folder: "विद्यालय वार्षिकोत्सव 2026", photosAlbumUrl: '', videos: [] },
  { order: 7, title: "स्कूल चलो अभियान", folder: "स्कूल चलो अभियान", photosAlbumUrl: '', videos: [] },
  { order: 8, title: "खेलकूद प्रतियोगिताएं", folder: "खेलकूद प्रतियोगिताएं", photosAlbumUrl: '', videos: [] },
  { order: 9, title: "शिक्षक अभिभावक संगोष्ठी", folder: "शिक्षक अभिभावक संगोष्ठी", photosAlbumUrl: '', videos: [] },
  { order: 10, title: "एक पेड़ मां के नाम कार्यक्रम", folder: "एक पेड़ मां के नाम अभियान", photosAlbumUrl: '', videos: [] },
  { order: 11, title: "होली कार्यक्रम 2026", folder: "होली कार्यक्रम 2026", photosAlbumUrl: '', videos: [] },
  { order: 12, title: "बीएसए महोदय का विद्यालय भ्रमण 2025", folder: "बीएसए महोदय का विद्यालय भ्रमण", photosAlbumUrl: '', videos: [] },
  { order: 13, title: "हिंदू नव वर्ष चैत्र प्रतिपदा उत्सव 2026", folder: "चैत्र प्रतिपदा उत्सव कार्यक्रम 2026", photosAlbumUrl: '', videos: [] },
  { order: 14, title: "नामांकन मेला 2026", folder: "नामांकन मेला 2026", photosAlbumUrl: '', videos: [] },
  { order: 15, title: "फेयरवेल कार्यक्रम 2026", folder: "फेयरवेल कार्यक्रम 2025 26", photosAlbumUrl: '', videos: [] },
  { order: 16, title: "स्मार्ट क्लास उद्घाटन", folder: "स्मार्ट क्लास उद्घाटन", photosAlbumUrl: '', videos: [] },
  { order: 17, title: "विद्यार्थी जन्मदिवस", folder: "विद्यार्थी जन्मदिवस", photosAlbumUrl: '', videos: [] },
  { order: 19, title: "कथावाचक सुश्री चारु चर्चिका कार्यक्रम 2026", folder: "कथावाचक सुश्री चारुचर्चिका कार्यक्रम", photosAlbumUrl: '', videos: [] },
  { order: 20, title: "कविताएं", folder: "कविताएं", photosAlbumUrl: '', videos: [] },
  { order: 22, title: "सुर्खियों में गोविंदपुर", folder: "सुर्खियों में गोविंदपुर", photosAlbumUrl: '', videos: [] },
];
